// symbolSize为当前点的值数值大小
// modularity_class 值相同的 nodes 点，即为同一类别且同一颜色
export const Graph = {
    links: [
        { id: '0', source: '1', target: '0', port: '0' },
        { id: '1', source: '1', target: '2', port: '1' },
        { id: '2', source: '1', target: '3', port: '2' },
        { id: '3', source: '1', target: '4', port: '3' },
        { id: '4', source: '1', target: '5', port: '4' },
        { id: '5', source: '1', target: '6', port: '5' },
        { id: '6', source: '1', target: '7', port: '6' },
        { id: '7', source: '2', target: '1', port: '7' },
        { id: '8', source: '2', target: '4', port: '8' },
        { id: '9', source: '2', target: '3', port: '9' },
        { id: '10', source: '7', target: '1', port: '10' },
        { id: '11', source: '8', target: '10', port: '11' },
        { id: '12', source: '9', target: '10', port: '12' },
        { id: '13', source: '10', target: '9', port: '13' },
        { id: '14', source: '3', target: '8', port: '14' },
    ],
    nodes: [
        {
            attributes: { modularity_class: 0 },
            itemStyle: null,
            category: 0,
            id: '0',
            label: { normal: { show: true } },
            name: '00000',
            symbolSize: 123,
            value: 28,
        },
        {
            attributes: { modularity_class: 1 },
            itemStyle: null,
            category: 1,
            id: '1',
            label: { normal: { show: true } },
            name: '11111',
            symbolSize: 11,
            value: 20,
        },
        {
            attributes: { modularity_class: 2 },
            itemStyle: null,
            category: 2,
            id: '2',
            label: { normal: { show: true } },
            name: '22222',
            symbolSize: 25,
            value: 2,
        },
        {
            attributes: { modularity_class: 3 },
            itemStyle: null,
            category: 3,
            id: '3',
            label: { normal: { show: true } },
            name: '33333',
            symbolSize: 43,
            value: 200,
        },
        {
            attributes: { modularity_class: 4 },
            itemStyle: null,
            category: 4,
            id: '4',
            label: { normal: { show: true } },
            name: '44444',
            symbolSize: 4,
            value: 56,
        },
        {
            attributes: { modularity_class: 5 },
            itemStyle: null,
            category: 5,
            id: '5',
            label: { normal: { show: true } },
            name: '55555',
            symbolSize: 45,
            value: 78,
        },
        {
            attributes: { modularity_class: 6 },
            itemStyle: null,
            category: 6,
            id: '6',
            label: { normal: { show: true } },
            name: '66666',
            symbolSize: 26,
            value: 7,
        },
        {
            attributes: { modularity_class: 7 },
            itemStyle: null,
            category: 7,
            id: '7',
            label: { normal: { show: true } },
            name: '77777',
            symbolSize: 7,
            value: 718,
        },
        {
            attributes: { modularity_class: 8 },
            itemStyle: null,
            category: 8,
            id: '8',
            label: { normal: { show: true } },
            name: '88888',
            symbolSize: 81,
            value: 38,
        },
        {
            attributes: { modularity_class: 9 },
            itemStyle: null,
            category: 9,
            id: '9',
            label: { normal: { show: true } },
            name: '99999',
            symbolSize: 9,
            value: 68,
        },
        {
            attributes: { modularity_class: 10 },
            itemStyle: null,
            category: 10,
            id: '10',
            label: { normal: { show: true } },
            name: '101010',
            symbolSize: 10,
            value: 28,
        },
    ],
};
